"""
API Schemas Package
"""

from api.schemas.auth import (
    UserCreate,
    UserLogin,
    Token,
    TokenPayload,
    RefreshTokenRequest,
    UserRole,
    TokenType,
    ACCESS_TOKEN_EXPIRE_SECONDS,
    REFRESH_TOKEN_EXPIRE_SECONDS,
)
from api.schemas.project import (
    ProjectCreate,
    ProjectUpdate,
    ProjectResponse,
    ProjectMemberAdd,
    ProjectMemberResponse,
    ProjectStatus,
    ProjectMemberRole,
)
from api.schemas.chapter import (
    ChapterCreate,
    ChapterUpdate,
    ChapterResponse,
    SectionCreate,
    SectionUpdate,
    SectionResponse,
    ReviewSubmit,
    ReviewResponse,
    ChapterStatus,
)
from api.schemas.term import (
    TermCreate,
    TermUpdate,
    TermResponse,
    DEFAULT_SEARCH_LIMIT,
    MAX_SEARCH_LIMIT,
)
from api.schemas.common import (
    PaginatedResponse,
    ErrorResponse,
    ErrorDetail,
    SuccessResponse,
    HealthResponse,
    MetricsResponse,
    LogEntry,
    PaginationParams,
    IDParams,
    ProjectIDParams,
    ChapterIDParams,
    ScanRequest,
    ScanResponse,
    DOIVerifyRequest,
    DOIVerifyResponse,
    RegulationVerifyRequest,
    RegulationVerifyResponse,
    SemanticScanRequest,
    SemanticScanResponse,
    ErrorCode,
    DEFAULT_PAGE,
    DEFAULT_PER_PAGE,
    MAX_PER_PAGE,
    API_VERSION,
    SortOrder,
)

__all__ = [
    # Auth
    "UserCreate",
    "UserLogin",
    "Token",
    "TokenPayload",
    "RefreshTokenRequest",
    "UserRole",
    "TokenType",
    "ACCESS_TOKEN_EXPIRE_SECONDS",
    "REFRESH_TOKEN_EXPIRE_SECONDS",
    # Project
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectMemberAdd",
    "ProjectMemberResponse",
    "ProjectStatus",
    "ProjectMemberRole",
    # Chapter
    "ChapterCreate",
    "ChapterUpdate",
    "ChapterResponse",
    "SectionCreate",
    "SectionUpdate",
    "SectionResponse",
    "ReviewSubmit",
    "ReviewResponse",
    "ChapterStatus",
    # Term
    "TermCreate",
    "TermUpdate",
    "TermResponse",
    "DEFAULT_SEARCH_LIMIT",
    "MAX_SEARCH_LIMIT",
    # Common
    "PaginatedResponse",
    "ErrorResponse",
    "ErrorDetail",
    "SuccessResponse",
    "HealthResponse",
    "MetricsResponse",
    "LogEntry",
    "PaginationParams",
    "IDParams",
    "ProjectIDParams",
    "ChapterIDParams",
    "ScanRequest",
    "ScanResponse",
    "DOIVerifyRequest",
    "DOIVerifyResponse",
    "RegulationVerifyRequest",
    "RegulationVerifyResponse",
    "SemanticScanRequest",
    "SemanticScanResponse",
    "ErrorCode",
    "DEFAULT_PAGE",
    "DEFAULT_PER_PAGE",
    "MAX_PER_PAGE",
    "API_VERSION",
    "SortOrder",
]
